"""
Nova Agent Export: happy_test_suhail_agent
Generated by Nova BYOA (Bring Your Own Agent)

Framework : LangGraph
Role      : specialist
Model     : gpt-4.1-20250414

This file defines the LangGraph agent graph.  server.py wraps it with a
FastAPI endpoint that implements the Nova External API contract, so you can
register this container back into Nova after deploying it.
"""

from __future__ import annotations

import os
from typing import Annotated, TypedDict, Sequence
import operator

from dotenv import load_dotenv
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode


# Load environment variables from a .env file in the working directory if
# present.
load_dotenv()


# ──────────────────────────────────────────────
# System prompt
# ──────────────────────────────────────────────
SYSTEM_PROMPT = """## Role & Persona
You are a nutritionist specializing in nutrition. Your expertise includes [key skills].

## Instructions

## Output Format
- Respond in bullet points.
- Keep responses concise and professional.

## Guardrails
- If uncertain, ask clarifying questions before proceeding.
- Do not try to diagnose the health issue.
- Always give supplements with before and after food."""


# ──────────────────────────────────────────────
# MCP server connection config (from environment)
# ──────────────────────────────────────────────
# No MCP servers attached to this agent


# ──────────────────────────────────────────────
# Tools
# ──────────────────────────────────────────────
# No tools were attached to this agent


TOOLS = []


# ──────────────────────────────────────────────
# Agent state
# ──────────────────────────────────────────────
class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], operator.add]


# ──────────────────────────────────────────────
# Model
# ──────────────────────────────────────────────
def _build_model() -> ChatOpenAI:
    return ChatOpenAI(
        model=os.environ.get("NOVA_MODEL", "gpt-4.1-20250414"),
        base_url=os.environ.get("LITELLM_BASE_URL", "http://localhost:4000"),
        api_key=os.environ.get("LITELLM_API_KEY", "sk-placeholder"),
        temperature=0,
    ).bind_tools(TOOLS)


# ──────────────────────────────────────────────
# Graph nodes
# ──────────────────────────────────────────────
def agent_node(state: AgentState) -> dict:
    """Call the LLM with the current message history."""
    model = _build_model()
    messages = [SystemMessage(content=SYSTEM_PROMPT)] + list(state["messages"])
    response = model.invoke(messages)
    return {"messages": [response]}


def should_continue(state: AgentState) -> str:
    """Route to tool execution or finish."""
    last = state["messages"][-1]
    if hasattr(last, "tool_calls") and last.tool_calls:
        return "tools"
    return END


# ──────────────────────────────────────────────
# Graph assembly
# ──────────────────────────────────────────────
tool_node = ToolNode(TOOLS)

workflow = StateGraph(AgentState)
workflow.add_node("agent", agent_node)
workflow.add_node("tools", tool_node)
workflow.set_entry_point("agent")
workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
workflow.add_edge("tools", "agent")

graph = workflow.compile()


# ──────────────────────────────────────────────
# Public entry point
# ──────────────────────────────────────────────
def run(messages: list[dict], config: dict | None = None) -> str:
    """
    Run the agent and return the final text response.

    Args:
        messages: list of {"role": "user"|"assistant"|"system", "content": str}
        config:   optional LangGraph run config

    Returns:
        The assistant's final text response.
    """
    lc_messages: list[BaseMessage] = []
    for m in messages:
        role = m.get("role", "user")
        content = m.get("content", "")
        if role == "user":
            lc_messages.append(HumanMessage(content=content))
        elif role == "assistant":
            lc_messages.append(AIMessage(content=content))
        elif role == "system":
            lc_messages.append(SystemMessage(content=content))

    result = graph.invoke({"messages": lc_messages}, config=config or {})
    last = result["messages"][-1]
    return last.content if hasattr(last, "content") else str(last)
